name: 💡 Feature Request
description: Suggest an idea for this repository
title: 'feature: '
body:
  - type: textarea
    attributes:
      label: Describe the Feature Request
      description: A clear and concise description of what the feature does.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe the Use Case
      description: A clear and concise use case for what problem this feature would solve.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe Preferred Solution
      description: A clear and concise description of how you want this feature to be added.
  - type: textarea
    attributes:
      label: Describe Alternatives
      description: A clear and concise description of any alternative solutions or features you have considered.
  - type: textarea
    attributes:
      label: Related Code
      description: If you are able to illustrate the feature request with an example, please provide it here.
  - type: textarea
    attributes:
      label: Additional Information
      description: List any other information that is relevant to your issue.
        Stack traces, related issues, suggestions on how to implement, Stack Overflow links, forum links, etc.
        Please upload any screenshots that your think are relevant.
  - type: markdown
    attributes:
      value: |
        Accepted features are likely to be converted into *User Story* issues linked to the feature request.
        Thank you for taking the time to fill out this feature request!
