# A workflow that tests this action

name: SARIF issue workflow

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  issues: write

jobs:
  issue:
    runs-on: ubuntu-latest
    name: Run the SARIF issue updater

    steps:

      - name: Harden Runner
        uses: step-security/harden-runner@248ae51c2e8cc9622ecf50685c8bf7150c6e8813
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - name: Checkout
        uses: actions/checkout@d0651293c4a5a52e711f25b41b05b2212f385d28

      - name: Post SARIF findings in the issue
        uses: tomwillis608/sarif-to-issue-action@bd897dccd956245db52aa3b2d94e80888ec63d20
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          branch: ${{ github.head_ref }}
          sarif-file: ./test/fixtures/odc.sarif
          title: "Build artifact: issue-test.yml workflow"
          labels: "build,expected"
          dry-run: false
          odc-sarif: true
